### ISSUE TITLE
Error in fail: missing mapping between machine architecture arm64 and goarch

### ISSUE THREAD

**Issue by tkaewplik** [plezentek/rules_wire#3]
# Describtion
Got message `Error in fail: missing mapping between machine architecture arm64 and goarch` when run `wire_injector` on macos M1 (arm64)

From the code below, should it be `elif` instead of `if`?

https://github.com/plezentek/rules_wire/blame/98f72cae33303890a855718f87798b209d50ccc3/wire/private/release.bzl#L50

**Comment by dmayle** [comment]
That's exactly the problem, thank you for the fix.  I should be able to push out a new release tomorrow

**Comment by dmayle** [comment]
In the meantime, you should be able to get running with this:

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_plezentek_rules_wire",
    commit = "403c680290493334536b3b7d51021c94cbd19897",
    remote = "https://github.com/plezentek/rules_wire",
)

load("@com_plezentek_rules_wire//wire:deps.bzl", "wire_register_toolchains", "wire_rules_dependencies")

wire_rules_dependencies()

wire_register_toolchains()
```

**Comment by tkaewplik** [comment]
Thank you for your swift reply.

After applying your code, I got an another issue.
It seems like the `arm64` is not supported yet.

https://github.com/tkaewplik/rules_wire/blob/main/wire/private/wire_versions.bzl
https://github.com/dmayle/wire/releases

**Comment by dmayle** [comment]
I don't think there's anything inherently architecture-specific about wire.  I'll try to cross-compile arm64 binaries when I issue the new release.

**Comment by dmayle** [comment]
I've published a new release of the wire binaries at: https://github.com/dmayle/wire/releases/tag/v0.6.0

**Comment by dmayle** [comment]
It was a bit more work than I'd expected since I had to update dependencies like rules_go, and stardoc broke along the way, but I've issued a new release of rules_wire that works with arm64.
